export enum WORKOUT_STEP_TYPE {
  WARMUP = 'WARMUP',
  COOLDOWN = 'COOLDOWN',
  INTERVAL_ACTIVE = 'INTERVAL_ACTIVE',
  INTERVAL_REST = 'INTERVAL_REST',
  STEADY = 'STEADY',
  REPEAT = 'REPEAT',
  FREE = 'FREE',
}
