export enum WORKOUT_DURATION_TYPE {
  TIME = 'TIME',
  DISTANCE = 'DISTANCE',
  CALORIES = 'CALORIES',
  HR_BELOW = 'HR_BELOW',
  HR_ABOVE = 'HR_ABOVE',
  LAP_BUTTON = 'LAP_BUTTON',
  OPEN = 'OPEN',
  REPS = 'REPS',
}
