import { m } from '@/paraglide/messages';

import { METRIC_TYPE } from '@openathlete/shared';

export const metricTypeLabelMap: Record<METRIC_TYPE, string> = {
  [METRIC_TYPE.WEIGHT]: m.metric_weight(),
  [METRIC_TYPE.HEIGHT]: m.metric_height(),
  [METRIC_TYPE.BMI]: m.metric_bmi(),
  [METRIC_TYPE.BODY_FAT]: m.metric_body_fat(),
  [METRIC_TYPE.MUSCLE_MASS]: m.metric_muscle_mass(),
  [METRIC_TYPE.BONE_MASS]: m.metric_bone_mass(),
  [METRIC_TYPE.BODY_WATER]: m.metric_body_water(),
  [METRIC_TYPE.DAILY_CALORIES]: m.metric_daily_calories(),
  [METRIC_TYPE.DAILY_ACTIVE_CALORIES]: m.metric_daily_active_calories(),
  [METRIC_TYPE.DAILY_BMR_CALORIES]: m.metric_daily_bmr_calories(),
  [METRIC_TYPE.DAILY_STEPS]: m.metric_daily_steps(),
  [METRIC_TYPE.DAILY_DISTANCE]: m.metric_daily_distance(),
  [METRIC_TYPE.DAILY_ACTIVE_MINUTES]: m.metric_daily_active_minutes(),
  [METRIC_TYPE.DAILY_MODERATE_MINUTES]: m.metric_daily_moderate_minutes(),
  [METRIC_TYPE.DAILY_VIGOROUS_MINUTES]: m.metric_daily_vigorous_minutes(),
  [METRIC_TYPE.DAILY_FLOORS]: m.metric_daily_floors(),
  [METRIC_TYPE.SLEEP_DURATION]: m.metric_sleep_duration(),
  [METRIC_TYPE.SLEEP_SCORE]: m.metric_sleep_score(),
  [METRIC_TYPE.SLEEP_REM_DURATION]: m.metric_sleep_rem_duration(),
  [METRIC_TYPE.SLEEP_DEEP_DURATION]: m.metric_sleep_deep_duration(),
  [METRIC_TYPE.SLEEP_LIGHT_DURATION]: m.metric_sleep_light_duration(),
  [METRIC_TYPE.SLEEP_AWAKE_DURATION]: m.metric_sleep_awake_duration(),
  [METRIC_TYPE.SLEEP_RESPIRATION_AVG]: m.metric_sleep_respiration_avg(),
  [METRIC_TYPE.SLEEP_SPO2_AVG]: m.metric_sleep_spo2_avg(),
  [METRIC_TYPE.NAP_DURATION]: m.metric_nap_duration(),
  [METRIC_TYPE.HOOPER_INDEX]: m.metric_hooper_index(),

  [METRIC_TYPE.HR_MAX]: m.metric_hr_max(),
  [METRIC_TYPE.HR_REST]: m.metric_hr_rest(),
  [METRIC_TYPE.HR_MIN_DAILY]: m.metric_hr_min_daily(),
  [METRIC_TYPE.HR_AVG_DAILY]: m.metric_hr_avg_daily(),
  [METRIC_TYPE.HR_MAX_DAILY]: m.metric_hr_max_daily(),
  [METRIC_TYPE.HR_RESERVE]: m.metric_hr_reserve(),
  [METRIC_TYPE.RMSSD]: m.metric_rmssd(),
  [METRIC_TYPE.HRV_LAST_NIGHT_AVG]: m.metric_hrv_last_night_avg(),
  [METRIC_TYPE.HRV_LAST_NIGHT_5MIN_HIGH]: m.metric_hrv_last_night_5min_high(),
  [METRIC_TYPE.SNAPSHOT_HEART_RATE_AVG]: m.metric_snapshot_heart_rate_avg(),
  [METRIC_TYPE.SNAPSHOT_STRESS_AVG]: m.metric_snapshot_stress_avg(),
  [METRIC_TYPE.SNAPSHOT_RESPIRATION_AVG]: m.metric_snapshot_respiration_avg(),
  [METRIC_TYPE.SNAPSHOT_SPO2_AVG]: m.metric_snapshot_spo2_avg(),
  [METRIC_TYPE.SNAPSHOT_SDNN]: m.metric_snapshot_sdnn(),
  [METRIC_TYPE.SNAPSHOT_RMSSD]: m.metric_snapshot_rmssd(),
  [METRIC_TYPE.RESPIRATION_RATE_AVG]: m.metric_respiration_rate_avg(),
  [METRIC_TYPE.PULSE_OX_AVG]: m.metric_pulse_ox_avg(),
  [METRIC_TYPE.PULSE_OX_MIN]: m.metric_pulse_ox_min(),
  [METRIC_TYPE.BLOOD_PRESSURE_SYSTOLIC]: m.metric_blood_pressure_systolic(),
  [METRIC_TYPE.BLOOD_PRESSURE_DIASTOLIC]: m.metric_blood_pressure_diastolic(),
  [METRIC_TYPE.BLOOD_PRESSURE_PULSE]: m.metric_blood_pressure_pulse(),
  [METRIC_TYPE.STRESS_AVERAGE]: m.metric_stress_average(),
  [METRIC_TYPE.STRESS_MAX]: m.metric_stress_max(),
  [METRIC_TYPE.STRESS_DURATION]: m.metric_stress_duration(),
  [METRIC_TYPE.STRESS_REST_DURATION]: m.metric_stress_rest_duration(),
  [METRIC_TYPE.STRESS_ACTIVITY_DURATION]: m.metric_stress_activity_duration(),
  [METRIC_TYPE.STRESS_LOW_DURATION]: m.metric_stress_low_duration(),
  [METRIC_TYPE.STRESS_MEDIUM_DURATION]: m.metric_stress_medium_duration(),
  [METRIC_TYPE.STRESS_HIGH_DURATION]: m.metric_stress_high_duration(),
  [METRIC_TYPE.BODY_BATTERY_CHARGED]: m.metric_body_battery_charged(),
  [METRIC_TYPE.BODY_BATTERY_DRAINED]: m.metric_body_battery_drained(),
  [METRIC_TYPE.SKIN_TEMP_DEVIATION]: m.metric_skin_temp_deviation(),

  [METRIC_TYPE.VMA]: m.metric_vma(),
  [METRIC_TYPE.CRITICAL_POWER_RUNNING]: m.metric_critical_power_running(),
  [METRIC_TYPE.CRITICAL_POWER_CYCLING]: m.metric_critical_power_cycling(),
  [METRIC_TYPE.VO2MAX]: m.metric_vo2max(),
  [METRIC_TYPE.VO2MAX_CYCLING]: m.metric_vo2max_cycling(),
  [METRIC_TYPE.FTP_RUNNING]: m.metric_ftp_running(),
  [METRIC_TYPE.FTP_CYCLING]: m.metric_ftp_cycling(),
  [METRIC_TYPE.VERTICAL_SPEED_AVG]: m.metric_vertical_speed_avg(),
  [METRIC_TYPE.VERTICAL_SPEED_MAX]: m.metric_vertical_speed_max(),
  [METRIC_TYPE.FITNESS_INDEX]: m.metric_fitness_index(),
  [METRIC_TYPE.FITNESS_AGE]: m.metric_fitness_age(),
};
