import { m } from '@/paraglide/messages';

import { SPORT_TYPE } from '@openathlete/shared';

export const sportTypeLabelMap: Record<SPORT_TYPE, string> = {
  [SPORT_TYPE.RUNNING]: m.sport_running(),
  [SPORT_TYPE.TRAIL_RUNNING]: m.sport_trail_running(),
  [SPORT_TYPE.CYCLING]: m.cycling(),
  [SPORT_TYPE.SWIMMING]: m.swimming(),
  [SPORT_TYPE.ROCK_CLIMBING]: m.sport_rock_climbing(),
  [SPORT_TYPE.HIKING]: m.sport_hiking(),
  [SPORT_TYPE.STRENGTH]: m.sport_strength(),
  [SPORT_TYPE.CROSSFIT]: m.sport_crossfit(),
  [SPORT_TYPE.YOGA]: m.sport_yoga(),
  [SPORT_TYPE.ALPINE_SKI]: m.sport_alpine_ski(),
  [SPORT_TYPE.BACKCOUNTRY_SKI]: m.sport_backcountry_ski(),
  [SPORT_TYPE.BADMINTON]: m.sport_badminton(),
  [SPORT_TYPE.CANOEING]: m.sport_canoeing(),
  [SPORT_TYPE.E_BIKE_RIDE]: m.sport_e_bike_ride(),
  [SPORT_TYPE.ELLIPTICAL]: m.sport_elliptical(),
  [SPORT_TYPE.E_MOUNTAIN_BIKE_RIDE]: m.sport_e_mountain_bike_ride(),
  [SPORT_TYPE.GOLF]: m.sport_golf(),
  [SPORT_TYPE.GRAVEL_RIDE]: m.sport_gravel_ride(),
  [SPORT_TYPE.HANDCYCLE]: m.sport_handcycle(),
  [SPORT_TYPE.HIGH_INTENSITY_INTERVAL_TRAINING]: m.sport_high_intensity_interval_training(),
  [SPORT_TYPE.ICE_SKATE]: m.sport_ice_skate(),
  [SPORT_TYPE.INLINE_SKATE]: m.sport_inline_skate(),
  [SPORT_TYPE.KAYAKING]: m.sport_kayaking(),
  [SPORT_TYPE.KITESURF]: m.sport_kitesurf(),
  [SPORT_TYPE.MOUNTAIN_BIKE_RIDE]: m.sport_mountain_bike_ride(),
  [SPORT_TYPE.NORDIC_SKI]: m.sport_nordic_ski(),
  [SPORT_TYPE.PICKLEBALL]: m.sport_pickleball(),
  [SPORT_TYPE.PILATES]: m.sport_pilates(),
  [SPORT_TYPE.RACQUETBALL]: m.sport_racquetball(),
  [SPORT_TYPE.ROLLER_SKI]: m.sport_roller_ski(),
  [SPORT_TYPE.ROWING]: m.sport_rowing(),
  [SPORT_TYPE.SAIL]: m.sport_sail(),
  [SPORT_TYPE.SKATEBOARD]: m.sport_skateboard(),
  [SPORT_TYPE.SNOWBOARD]: m.sport_snowboard(),
  [SPORT_TYPE.SNOWSHOE]: m.sport_snowshoe(),
  [SPORT_TYPE.SOCCER]: m.sport_soccer(),
  [SPORT_TYPE.SQUASH]: m.sport_squash(),
  [SPORT_TYPE.STAIR_STEPPER]: m.sport_stair_stepper(),
  [SPORT_TYPE.STAND_UP_PADDLING]: m.sport_stand_up_paddling(),
  [SPORT_TYPE.SURFING]: m.sport_surfing(),
  [SPORT_TYPE.TABLE_TENNIS]: m.sport_table_tennis(),
  [SPORT_TYPE.TENNIS]: m.sport_tennis(),
  [SPORT_TYPE.VELOMOBILE]: m.sport_velomobile(),
  [SPORT_TYPE.VIRTUAL_RIDE]: m.sport_virtual_ride(),
  [SPORT_TYPE.VIRTUAL_ROW]: m.sport_virtual_row(),
  [SPORT_TYPE.VIRTUAL_RUN]: m.sport_virtual_run(),
  [SPORT_TYPE.WALK]: m.sport_walk(),
  [SPORT_TYPE.WEIGHT_TRAINING]: m.sport_weight_training(),
  [SPORT_TYPE.WHEELCHAIR]: m.sport_wheelchair(),
  [SPORT_TYPE.WINDSURF]: m.sport_windsurf(),
  [SPORT_TYPE.WORKOUT]: m.sport_workout(),
  [SPORT_TYPE.OTHER]: m.sport_other(),
};
