import { METRIC_TYPE } from '../types/misc/core/metric-type.enum';

export const metricsByCategory: Record<string, METRIC_TYPE[]> = {
  health_composition: [
    METRIC_TYPE.WEIGHT,
    METRIC_TYPE.HEIGHT,
    METRIC_TYPE.BMI,
    METRIC_TYPE.BODY_FAT,
    METRIC_TYPE.MUSCLE_MASS,
    METRIC_TYPE.DAILY_CALORIES,
    METRIC_TYPE.DAILY_STEPS,
    METRIC_TYPE.SLEEP_DURATION,
    METRIC_TYPE.SLEEP_SCORE,
    METRIC_TYPE.HOOPER_INDEX,
  ],
  cardiac: [
    METRIC_TYPE.HR_MAX,
    METRIC_TYPE.HR_REST,
    METRIC_TYPE.HR_RESERVE,
    METRIC_TYPE.RMSSD,
  ],
  performance_physiology: [
    METRIC_TYPE.VMA,
    METRIC_TYPE.CRITICAL_POWER_RUNNING,
    METRIC_TYPE.CRITICAL_POWER_CYCLING,
    METRIC_TYPE.VO2MAX,
    METRIC_TYPE.FTP_RUNNING,
    METRIC_TYPE.FTP_CYCLING,
    METRIC_TYPE.VERTICAL_SPEED_AVG,
    METRIC_TYPE.VERTICAL_SPEED_MAX,
    METRIC_TYPE.FITNESS_INDEX,
  ],
};
