import { SpeedUnit } from '../types/misc/core/metrics';
import { SPORT_TYPE } from '../types/misc/core/sport-type.enum';

export interface SportStatisticsConfig {
  /** Whether to show distance */
  showDistance: boolean;
  /** Whether to show speed/pace */
  showSpeed: boolean;
  /** Whether to show max speed */
  showMaxSpeed: boolean;
  /** Whether to show GAP (Grade Adjusted Pace) */
  showGap: boolean;
  /** Whether to show elevation gain */
  showElevation: boolean;
  /** Whether to show heart rate */
  showHeartrate: boolean;
  /** Whether to show power */
  showPower: boolean;
  /** Whether to show cadence */
  showCadence: boolean;
  /** Whether to show splits */
  showSplits: boolean;
  /** Speed unit to use for this sport */
  speedUnit: SpeedUnit;
  /** Label for speed/pace (e.g., "Pace", "Speed") */
  speedLabel: 'pace' | 'speed';
}

/**
 * Configuration for statistics and units per sport type
 */
export const SPORT_CONFIG: Record<SPORT_TYPE, SportStatisticsConfig> = {
  // Running sports - use pace (min/km)
  [SPORT_TYPE.RUNNING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: true,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: true,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.TRAIL_RUNNING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: true,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: true,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.VIRTUAL_RUN]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: true,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.WALK]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.WHEELCHAIR]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },

  // Cycling sports - use speed (km/h)
  [SPORT_TYPE.CYCLING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.E_BIKE_RIDE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.GRAVEL_RIDE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.MOUNTAIN_BIKE_RIDE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.E_MOUNTAIN_BIKE_RIDE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.HANDCYCLE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.VELOMOBILE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.VIRTUAL_RIDE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Swimming - use pace (min/100m)
  [SPORT_TYPE.SWIMMING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: true,
    speedUnit: 'min/km', // Could be adapted to min/100m if needed
    speedLabel: 'pace',
  },

  // Water sports - use speed (km/h)
  [SPORT_TYPE.CANOEING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.KAYAKING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.ROWING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.VIRTUAL_ROW]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.STAND_UP_PADDLING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SAIL]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.KITESURF]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.WINDSURF]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SURFING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Skiing sports - use speed (km/h)
  [SPORT_TYPE.ALPINE_SKI]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.BACKCOUNTRY_SKI]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.NORDIC_SKI]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.ROLLER_SKI]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SNOWBOARD]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SNOWSHOE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },

  // Other outdoor activities
  [SPORT_TYPE.HIKING]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.ROCK_CLIMBING]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },

  // Skating sports - use speed (km/h)
  [SPORT_TYPE.ICE_SKATE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.INLINE_SKATE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SKATEBOARD]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Indoor/Equipment-based activities
  [SPORT_TYPE.ELLIPTICAL]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: true,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.STAIR_STEPPER]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Strength and fitness
  [SPORT_TYPE.STRENGTH]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.WEIGHT_TRAINING]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.CROSSFIT]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.HIGH_INTENSITY_INTERVAL_TRAINING]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.WORKOUT]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Mind-body activities
  [SPORT_TYPE.YOGA]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.PILATES]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Racquet sports
  [SPORT_TYPE.BADMINTON]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.PICKLEBALL]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.RACQUETBALL]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.SQUASH]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.TABLE_TENNIS]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.TENNIS]: {
    showDistance: false,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },

  // Other sports
  [SPORT_TYPE.SOCCER]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.GOLF]: {
    showDistance: true,
    showSpeed: false,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: false,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  // Multisport activities
  [SPORT_TYPE.TRIATHLON]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.DUATHLON]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.AQUATHLON]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: true,
    speedUnit: 'min/km',
    speedLabel: 'pace',
  },
  [SPORT_TYPE.AQUABIKE]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: true,
    showGap: false,
    showElevation: false,
    showHeartrate: true,
    showPower: true,
    showCadence: true,
    showSplits: true,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
  [SPORT_TYPE.OTHER]: {
    showDistance: true,
    showSpeed: true,
    showMaxSpeed: false,
    showGap: false,
    showElevation: true,
    showHeartrate: true,
    showPower: false,
    showCadence: false,
    showSplits: false,
    speedUnit: 'km/h',
    speedLabel: 'speed',
  },
};

/**
 * Get the speed unit for a given sport
 */
export function getSpeedUnitForSport(sport: SPORT_TYPE): SpeedUnit {
  return SPORT_CONFIG[sport].speedUnit;
}

/**
 * Get the full configuration for a given sport
 */
export function getSportConfig(sport: SPORT_TYPE): SportStatisticsConfig {
  return SPORT_CONFIG[sport];
}
