export const agentKeys = {
  root: 'AgentAPI',
  createThread: 'AgentAPI.createThread',
  getThread: 'AgentAPI.getThread',
  getUserThreads: 'AgentAPI.getUserThreads',
  updateThread: 'AgentAPI.updateThread',
  deleteThread: 'AgentAPI.deleteThread',
  createMessage: 'AgentAPI.createMessage',
  getThreadMessages: 'AgentAPI.getThreadMessages',
  deleteMessage: 'AgentAPI.deleteMessage',
  createBlock: 'AgentAPI.createBlock',
  updateBlock: 'AgentAPI.updateBlock',
  deleteBlock: 'AgentAPI.deleteBlock',
  sendMessage: 'AgentAPI.sendMessage',
} as const;
