import { ZodValidationPipe } from 'nestjs-zod';

import { Body, Controller, Post, UseGuards } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import {
  ApiBearerAuth,
  ApiBody,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';

import {
  CreateWorkoutStepDto,
  EVENT_TYPE,
  FeatureName,
  GenerateEventDto,
  GenerateEventResponseDto,
  ModifyEventDto,
  ModifyEventResponseDto,
  SPORT_TYPE,
  UpdateEventDto,
  WORKOUT_DURATION_TYPE,
  WORKOUT_STEP_TYPE,
  WORKOUT_TARGET_TYPE,
  generateEventDtoSchema,
  modifyEventDtoSchema,
} from '@openathlete/shared';

import { JwtUser, UserTypeGuard } from 'src/modules/auth';
import { AuthUser } from 'src/modules/auth/decorators/user.decorator';
import { FeatureAccessGuard, RequireFeature } from 'src/modules/subscription';

import { EventGenerationService } from '../services/event-generation.service';
import { EventModificationService } from '../services/event-modification.service';

@ApiTags('Agent')
@Controller('agent/ai')
export class AIFeaturesController {
  constructor(
    private readonly eventGenerationService: EventGenerationService,
    private readonly eventModificationService: EventModificationService,
  ) {}

  @UseGuards(AuthGuard('jwt'), UserTypeGuard, FeatureAccessGuard)
  @RequireFeature(FeatureName.AI_GENERATION)
  @ApiBearerAuth()
  @Post('events/generate')
  @ApiOperation({
    summary: 'Generate a training event using AI',
    description:
      "Generates a complete training event using AI based on a natural language prompt. The AI considers the athlete's training zones, latest metrics, and training load to create a personalized workout. The generated event includes a structured workout with steps (warmup, intervals, cooldown, etc.), targets (heart rate zones, pace, power), and goals (duration, distance, elevation, RPE). The event is scheduled for the specified date with a default start time of 8:00 AM. Requires AI_GENERATION feature access (available in paid subscription plans).",
  })
  @ApiBody({
    description: 'Event generation request',
    schema: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description:
            'Natural language description of the desired training event (1-500 characters)',
          example:
            'Create a 45-minute interval run with 5x 3-minute intervals at threshold pace',
          minLength: 1,
          maxLength: 500,
        },
        date: {
          type: 'string',
          format: 'date',
          description: 'ISO date string for the event date',
          example: '2024-01-15',
        },
      },
      required: ['prompt', 'date'],
    },
  })
  @ApiResponse({
    status: 201,
    description: 'Training event generated successfully',
    schema: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: [EVENT_TYPE.TRAINING],
          example: 'TRAINING',
        },
        name: {
          type: 'string',
          description: 'Event name generated by AI',
          example: 'Interval Run - 5x 3min Threshold',
        },
        description: {
          type: 'string',
          description: 'Event description',
          example: 'A structured interval run focusing on threshold pace',
        },
        startDate: {
          type: 'string',
          format: 'date-time',
          description:
            'Event start date and time (defaults to 8:00 AM on specified date)',
          example: '2024-01-15T08:00:00.000Z',
        },
        endDate: {
          type: 'string',
          format: 'date-time',
          description:
            'Event end date and time (calculated from goalDuration or defaults to 1 hour)',
          example: '2024-01-15T08:45:00.000Z',
        },
        sport: {
          type: 'string',
          enum: Object.values(SPORT_TYPE),
          example: 'RUNNING',
        },
        goalDuration: {
          type: 'number',
          nullable: true,
          description: 'Target duration in seconds',
          example: 2700,
        },
        goalDistance: {
          type: 'number',
          nullable: true,
          description: 'Target distance in meters',
          example: 8000,
        },
        goalElevationGain: {
          type: 'number',
          nullable: true,
          description: 'Target elevation gain in meters',
          example: 200,
        },
        goalRpe: {
          type: 'number',
          nullable: true,
          description: 'Target Rate of Perceived Exertion (1-10)',
          example: 7,
        },
        athleteId: {
          type: 'number',
          description: 'ID of the athlete for whom the event is generated',
          example: 1,
        },
        workout: {
          type: 'object',
          nullable: true,
          description: 'Structured workout with steps and targets',
          properties: {
            steps: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  stepType: {
                    type: 'string',
                    enum: Object.values(WORKOUT_STEP_TYPE),
                  },
                  name: { type: 'string', nullable: true },
                  durationType: {
                    type: 'string',
                    enum: Object.values(WORKOUT_DURATION_TYPE),
                    nullable: true,
                  },
                  durationValue: { type: 'number', nullable: true },
                  notes: { type: 'string', nullable: true },
                  targets: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        targetType: {
                          type: 'string',
                          enum: Object.values(WORKOUT_TARGET_TYPE),
                        },
                        targetMin: { type: 'number', nullable: true },
                        targetMax: { type: 'number', nullable: true },
                        targetValue: { type: 'number', nullable: true },
                        metricType: { type: 'string', nullable: true },
                      },
                    },
                  },
                  repeatBlock: {
                    type: 'object',
                    nullable: true,
                    properties: {
                      repetitions: { type: 'number' },
                      childSteps: { type: 'array', items: { type: 'object' } },
                    },
                  },
                },
              },
            },
          },
        },
      },
      required: [
        'type',
        'name',
        'description',
        'startDate',
        'endDate',
        'sport',
        'athleteId',
      ],
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid prompt or date format',
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description:
      'Forbidden - AI_GENERATION feature access required (paid subscription)',
  })
  @ApiResponse({
    status: 500,
    description:
      'Internal server error - AI generation failed or validation error',
  })
  async generateEvent(
    @JwtUser() user: AuthUser,
    @Body(new ZodValidationPipe(generateEventDtoSchema)) dto: GenerateEventDto,
  ): Promise<GenerateEventResponseDto> {
    const athleteId = user.athlete?.athlete_id || user.user_id;

    const parsedDate = new Date(dto.date);
    const year = parsedDate.getFullYear();
    const month = parsedDate.getMonth();
    const day = parsedDate.getDate();
    const eventDate = new Date(year, month, day, 0, 0, 0, 0);

    const generatedEvent =
      await this.eventGenerationService.generateTrainingEvent(
        dto.prompt,
        eventDate,
        athleteId,
      );

    const startDate = new Date(year, month, day, 8, 0, 0, 0);

    const endDate = new Date(startDate);
    if (generatedEvent.goalDuration) {
      endDate.setSeconds(endDate.getSeconds() + generatedEvent.goalDuration);
    } else {
      endDate.setHours(9, 0, 0, 0); // Default 1 hour
    }

    const transformedWorkout = generatedEvent.workout
      ? {
          steps: generatedEvent.workout.steps.map((step) => {
            const baseStep: CreateWorkoutStepDto = {
              stepType: step.stepType,
              name: step.name ?? null,
              durationType: step.durationType ?? null,
              durationValue: step.durationValue ?? null,
              notes: step.notes ?? null,
              targets: (step.targets || []).map((target) => ({
                targetType: target.targetType,
                targetMin: target.targetMin ?? null,
                targetMax: target.targetMax ?? null,
                targetValue: target.targetValue ?? null,
                metricType: target.metricType ?? null,
              })),
            };

            if (step.repeatBlock) {
              return {
                ...baseStep,
                repeatBlock: {
                  repetitions: step.repeatBlock.repetitions,
                  childSteps: step.repeatBlock.childSteps.map(
                    (childStep): CreateWorkoutStepDto => ({
                      stepType: childStep.stepType,
                      name: childStep.name ?? null,
                      durationType: childStep.durationType ?? null,
                      durationValue: childStep.durationValue ?? null,
                      notes: childStep.notes ?? null,
                      targets: (childStep.targets || []).map((target) => ({
                        targetType: target.targetType,
                        targetMin: target.targetMin ?? null,
                        targetMax: target.targetMax ?? null,
                        targetValue: target.targetValue ?? null,
                        metricType: target.metricType ?? null,
                      })),
                    }),
                  ),
                },
              } as CreateWorkoutStepDto;
            }

            return baseStep;
          }),
        }
      : undefined;

    const result: GenerateEventResponseDto = {
      type: EVENT_TYPE.TRAINING,
      name: generatedEvent.name,
      description: generatedEvent.description || '',
      startDate,
      endDate,
      sport: generatedEvent.sport,
      goalDuration: generatedEvent.goalDuration,
      athleteId,
      ...(transformedWorkout ? { workout: transformedWorkout } : {}),
    };

    return result;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard, FeatureAccessGuard)
  @RequireFeature(FeatureName.AI_GENERATION)
  @ApiBearerAuth()
  @Post('events/modify')
  @ApiOperation({
    summary: 'Modify an existing training event using AI',
    description:
      "Modifies an existing training event using AI based on a natural language prompt. The AI considers the current event structure, athlete's training zones, latest metrics, and training load to apply the requested modifications. This is a COMPLETE UPDATE operation - the AI returns the full, complete event with all workout steps. The modification can change event details (name, description, goals), adjust workout structure, modify targets, or add/remove steps. Requires AI_GENERATION feature access (available in paid subscription plans).",
  })
  @ApiBody({
    description: 'Event modification request',
    schema: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description:
            'Natural language description of the desired modifications (1-500 characters)',
          example: 'Make the intervals longer and add a 10-minute warmup',
          minLength: 1,
          maxLength: 500,
        },
        eventData: {
          type: 'object',
          description: 'Current event data to be modified',
          properties: {
            type: {
              type: 'string',
              enum: [EVENT_TYPE.TRAINING],
              example: 'TRAINING',
            },
            name: { type: 'string', example: 'Interval Run' },
            description: {
              type: 'string',
              example: 'A structured interval run',
            },
            sport: {
              type: 'string',
              enum: Object.values(SPORT_TYPE),
              example: 'RUNNING',
            },
            startDate: {
              type: 'string',
              format: 'date-time',
              example: '2024-01-15T08:00:00.000Z',
            },
            endDate: {
              type: 'string',
              format: 'date-time',
              example: '2024-01-15T08:45:00.000Z',
            },
            goalDuration: { type: 'number', nullable: true },
            goalDistance: { type: 'number', nullable: true },
            goalElevationGain: { type: 'number', nullable: true },
            goalRpe: { type: 'number', nullable: true },
            workout: {
              type: 'object',
              nullable: true,
              properties: {
                steps: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      stepType: { type: 'string' },
                      name: { type: 'string', nullable: true },
                      durationType: { type: 'string', nullable: true },
                      durationValue: { type: 'number', nullable: true },
                      notes: { type: 'string', nullable: true },
                      targets: { type: 'array', items: { type: 'object' } },
                      repeatBlock: {
                        type: 'object',
                        nullable: true,
                        properties: {
                          repetitions: { type: 'number' },
                          childSteps: {
                            type: 'array',
                            items: { type: 'object' },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
          required: [
            'type',
            'name',
            'description',
            'sport',
            'startDate',
            'endDate',
          ],
        },
      },
      required: ['prompt', 'eventData'],
    },
  })
  @ApiResponse({
    status: 200,
    description: 'Training event modified successfully',
    schema: {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          enum: [EVENT_TYPE.TRAINING],
          example: 'TRAINING',
        },
        name: {
          type: 'string',
          description: 'Updated event name',
          example: 'Modified Interval Run',
        },
        description: {
          type: 'string',
          description: 'Updated event description',
          example: 'A structured interval run with longer intervals',
        },
        startDate: {
          type: 'string',
          format: 'date-time',
          description: 'Event start date and time',
          example: '2024-01-15T08:00:00.000Z',
        },
        endDate: {
          type: 'string',
          format: 'date-time',
          description: 'Event end date and time',
          example: '2024-01-15T09:00:00.000Z',
        },
        sport: {
          type: 'string',
          enum: Object.values(SPORT_TYPE),
          example: 'RUNNING',
        },
        goalDuration: {
          type: 'number',
          nullable: true,
          description: 'Target duration in seconds',
          example: 3600,
        },
        goalDistance: {
          type: 'number',
          nullable: true,
          description: 'Target distance in meters',
          example: 10000,
        },
        goalElevationGain: {
          type: 'number',
          nullable: true,
          description: 'Target elevation gain in meters',
          example: 300,
        },
        goalRpe: {
          type: 'number',
          nullable: true,
          description: 'Target Rate of Perceived Exertion (1-10)',
          example: 8,
        },
        workout: {
          type: 'object',
          nullable: true,
          description: 'Updated structured workout with all steps',
          properties: {
            steps: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  stepType: {
                    type: 'string',
                    enum: Object.values(WORKOUT_STEP_TYPE),
                  },
                  name: { type: 'string', nullable: true },
                  durationType: {
                    type: 'string',
                    enum: Object.values(WORKOUT_DURATION_TYPE),
                    nullable: true,
                  },
                  durationValue: { type: 'number', nullable: true },
                  notes: { type: 'string', nullable: true },
                  targets: {
                    type: 'array',
                    items: {
                      type: 'object',
                      properties: {
                        targetType: {
                          type: 'string',
                          enum: Object.values(WORKOUT_TARGET_TYPE),
                        },
                        targetMin: { type: 'number', nullable: true },
                        targetMax: { type: 'number', nullable: true },
                        targetValue: { type: 'number', nullable: true },
                        metricType: { type: 'string', nullable: true },
                      },
                    },
                  },
                  repeatBlock: {
                    type: 'object',
                    nullable: true,
                    properties: {
                      repetitions: { type: 'number' },
                      childSteps: { type: 'array', items: { type: 'object' } },
                    },
                  },
                },
              },
            },
          },
        },
      },
      required: [
        'type',
        'name',
        'description',
        'startDate',
        'endDate',
        'sport',
      ],
    },
  })
  @ApiResponse({
    status: 400,
    description: 'Bad request - invalid prompt or event data',
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description:
      'Forbidden - AI_GENERATION feature access required (paid subscription)',
  })
  @ApiResponse({
    status: 500,
    description:
      'Internal server error - AI modification failed or validation error',
  })
  async modifyEvent(
    @JwtUser() user: AuthUser,
    @Body(new ZodValidationPipe(modifyEventDtoSchema)) dto: ModifyEventDto,
  ): Promise<ModifyEventResponseDto> {
    const athleteId = user.athlete?.athlete_id || user.user_id;

    const modifiedEvent =
      await this.eventModificationService.modifyTrainingEvent(
        dto.prompt,
        athleteId,
        dto.eventData,
      );

    const startDate = new Date(modifiedEvent.startDate);
    const endDate = new Date(modifiedEvent.endDate);

    const transformedWorkout = modifiedEvent.workout
      ? {
          steps: modifiedEvent.workout.steps.map((step) => {
            const baseStep: CreateWorkoutStepDto = {
              stepType: step.stepType,
              name: step.name ?? null,
              durationType: step.durationType ?? null,
              durationValue: step.durationValue ?? null,
              notes: step.notes ?? null,
              targets: (step.targets || []).map((target) => ({
                targetType: target.targetType,
                targetMin: target.targetMin ?? null,
                targetMax: target.targetMax ?? null,
                targetValue: target.targetValue ?? null,
                metricType: target.metricType ?? null,
              })),
            };

            if (step.repeatBlock) {
              return {
                ...baseStep,
                repeatBlock: {
                  repetitions: step.repeatBlock.repetitions,
                  childSteps: step.repeatBlock.childSteps.map(
                    (childStep): CreateWorkoutStepDto => ({
                      stepType: childStep.stepType,
                      name: childStep.name ?? null,
                      durationType: childStep.durationType ?? null,
                      durationValue: childStep.durationValue ?? null,
                      notes: childStep.notes ?? null,
                      targets: (childStep.targets || []).map((target) => ({
                        targetType: target.targetType,
                        targetMin: target.targetMin ?? null,
                        targetMax: target.targetMax ?? null,
                        targetValue: target.targetValue ?? null,
                        metricType: target.metricType ?? null,
                      })),
                    }),
                  ),
                },
              } as CreateWorkoutStepDto;
            }
            return baseStep;
          }),
        }
      : modifiedEvent.workout === null
        ? null
        : undefined;

    const result: ModifyEventResponseDto = {
      type: EVENT_TYPE.TRAINING,
      name: modifiedEvent.name,
      description: modifiedEvent.description || '',
      startDate,
      endDate,
      sport: modifiedEvent.sport,
      goalDuration: modifiedEvent.goalDuration ?? undefined,
      goalDistance: modifiedEvent.goalDistance ?? undefined,
      goalElevationGain: modifiedEvent.goalElevationGain ?? undefined,
      goalRpe: modifiedEvent.goalRpe ?? undefined,
      ...(transformedWorkout ? { workout: transformedWorkout } : {}),
    } as UpdateEventDto;

    return result;
  }
}
