import { ZodValidationPipe } from 'nestjs-zod';

import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  ParseIntPipe,
  Post,
  Put,
  UseGuards,
} from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import {
  ApiBearerAuth,
  ApiBody,
  ApiOperation,
  ApiParam,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';

import {
  AgentBlockStatus,
  AgentBlockType,
  AgentMessageRole,
  AgentMessageStatus,
} from '@openathlete/database';
import {
  CreateMessageDto,
  CreateThreadDto,
  UpdateThreadDto,
  createMessageDtoSchema,
  createThreadDtoSchema,
  updateThreadDtoSchema,
} from '@openathlete/shared';

import { JwtUser, UserTypeGuard } from 'src/modules/auth';
import { AuthUser } from 'src/modules/auth/decorators/user.decorator';

import { MastraAgentService } from '../services/mastra-agent.service';
import { MessageService } from '../services/message.service';
import { ThreadService } from '../services/thread.service';

@ApiTags('Agent')
@Controller('agent')
export class ChatAgentController {
  constructor(
    private threadService: ThreadService,
    private messageService: MessageService,
    private mastraAgentService: MastraAgentService,
  ) {}

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Post('threads')
  @ApiOperation({
    summary: 'Create a new agent conversation thread',
    description:
      'Creates a new conversation thread for interacting with the AI coach agent. Each thread represents a separate conversation session. The thread is automatically associated with the authenticated user. Metadata can be stored for custom thread configuration.',
  })
  @ApiBody({
    description: 'Thread creation data',
    schema: {
      type: 'object',
      properties: {
        title: {
          type: 'string',
          nullable: true,
          description:
            'Thread title (optional, can be auto-generated by the agent)',
          example: 'Training Plan Discussion',
        },
        metadata: {
          type: 'object',
          nullable: true,
          description: 'Custom metadata to store with the thread',
          example: { context: 'training-plan' },
        },
      },
    },
  })
  @ApiResponse({
    status: 201,
    description: 'Thread created successfully',
    schema: {
      type: 'object',
      properties: {
        threadId: { type: 'number', example: 1 },
        userId: { type: 'number', example: 1 },
        title: {
          type: 'string',
          nullable: true,
          example: 'Training Plan Discussion',
        },
        metadata: { type: 'object', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        messages: { type: 'array', items: { type: 'object' } },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  async createThread(
    @JwtUser() user: AuthUser,
    @Body(new ZodValidationPipe(createThreadDtoSchema)) dto: CreateThreadDto,
  ) {
    return this.threadService.createThread(user, dto);
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Get('threads')
  @ApiOperation({
    summary: 'Get all agent conversation threads for the authenticated user',
    description:
      'Retrieves all conversation threads created by the authenticated user. Threads are ordered by most recently updated first. Each thread includes its messages and blocks.',
  })
  @ApiResponse({
    status: 200,
    description: 'List of threads retrieved successfully',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          threadId: { type: 'number', example: 1 },
          userId: { type: 'number', example: 1 },
          title: {
            type: 'string',
            nullable: true,
            example: 'Training Plan Discussion',
          },
          metadata: { type: 'object', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          messages: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                messageId: { type: 'number' },
                threadId: { type: 'number' },
                role: {
                  type: 'string',
                  enum: Object.values(AgentMessageRole),
                },
                status: {
                  type: 'string',
                  enum: Object.values(AgentMessageStatus),
                },
                blocks: { type: 'array' },
              },
            },
          },
        },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  async getUserThreads(@JwtUser() user: AuthUser) {
    const threads = await this.threadService.getUserThreads(user);
    return threads;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Get('threads/:threadId')
  @ApiOperation({
    summary: 'Get an agent conversation thread by ID',
    description:
      'Retrieves a specific conversation thread by ID. Only the thread owner can access it. The thread includes all messages and blocks, ordered by creation date. Uses CASL authorization to verify access permissions.',
  })
  @ApiParam({
    name: 'threadId',
    type: Number,
    description: 'ID of the thread to retrieve',
    example: 1,
  })
  @ApiResponse({
    status: 200,
    description: 'Thread retrieved successfully',
    schema: {
      type: 'object',
      properties: {
        threadId: { type: 'number', example: 1 },
        userId: { type: 'number', example: 1 },
        title: {
          type: 'string',
          nullable: true,
          example: 'Training Plan Discussion',
        },
        metadata: { type: 'object', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        messages: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              messageId: { type: 'number' },
              threadId: { type: 'number' },
              role: {
                type: 'string',
                enum: Object.values(AgentMessageRole),
              },
              status: {
                type: 'string',
                enum: Object.values(AgentMessageStatus),
              },
              metadata: { type: 'object', nullable: true },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
              blocks: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    blockId: { type: 'number' },
                    messageId: { type: 'number' },
                    type: {
                      type: 'string',
                      enum: Object.values(AgentBlockType),
                    },
                    order: { type: 'number' },
                    content: { type: 'string' },
                    status: {
                      type: 'string',
                      enum: Object.values(AgentBlockStatus),
                    },
                    toolName: { type: 'string', nullable: true },
                    toolInput: { type: 'object', nullable: true },
                    toolOutput: { type: 'object', nullable: true },
                    chartType: { type: 'string', nullable: true },
                    chartData: { type: 'object', nullable: true },
                    error: { type: 'string', nullable: true },
                    metadata: { type: 'object', nullable: true },
                  },
                },
              },
            },
          },
        },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this thread',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - thread not found',
  })
  async getThreadById(
    @JwtUser() user: AuthUser,
    @Param('threadId', ParseIntPipe) threadId: number,
  ) {
    const thread = await this.threadService.getThreadById(user, threadId);
    return thread;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Put('threads/:threadId')
  @ApiOperation({
    summary: 'Update an agent conversation thread',
    description:
      'Updates a conversation thread (title and/or metadata). Only the thread owner can update it. Verifies access using CASL authorization before updating.',
  })
  @ApiParam({
    name: 'threadId',
    type: Number,
    description: 'ID of the thread to update',
    example: 1,
  })
  @ApiBody({
    description: 'Thread update data',
    schema: {
      type: 'object',
      properties: {
        title: {
          type: 'string',
          nullable: true,
          description: 'New thread title',
          example: 'Updated Training Plan Discussion',
        },
        metadata: {
          type: 'object',
          nullable: true,
          description: 'Updated metadata',
          example: { context: 'updated-context' },
        },
      },
    },
  })
  @ApiResponse({
    status: 200,
    description: 'Thread updated successfully',
    schema: {
      type: 'object',
      properties: {
        threadId: { type: 'number', example: 1 },
        title: {
          type: 'string',
          nullable: true,
          example: 'Updated Training Plan Discussion',
        },
        metadata: { type: 'object', nullable: true },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this thread',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - thread not found',
  })
  async updateThread(
    @JwtUser() user: AuthUser,
    @Param('threadId', ParseIntPipe) threadId: number,
    @Body(new ZodValidationPipe(updateThreadDtoSchema)) dto: UpdateThreadDto,
  ) {
    const thread = await this.threadService.updateThread(user, threadId, dto);
    return thread;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Delete('threads/:threadId')
  @ApiOperation({
    summary: 'Delete an agent conversation thread',
    description:
      'Permanently deletes a conversation thread and all its messages and blocks. Only the thread owner can delete it. Verifies access using CASL authorization before deleting. This operation cannot be undone.',
  })
  @ApiParam({
    name: 'threadId',
    type: Number,
    description: 'ID of the thread to delete',
    example: 1,
  })
  @ApiResponse({
    status: 200,
    description: 'Thread deleted successfully',
    schema: {
      type: 'object',
      properties: {
        success: { type: 'boolean', example: true },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this thread',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - thread not found',
  })
  deleteThread(
    @JwtUser() user: AuthUser,
    @Param('threadId', ParseIntPipe) threadId: number,
  ) {
    return this.threadService.deleteThread(user, threadId);
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Post('messages')
  @ApiOperation({
    summary: 'Create a new message in an agent conversation thread',
    description:
      'Creates a new message in an agent conversation thread. Messages can be from USER, ASSISTANT, SYSTEM, or TOOL roles. Messages can contain multiple blocks (text, tool calls, charts, etc.). Verifies that the user has access to the thread before creating the message.',
  })
  @ApiBody({
    description: 'Message creation data',
    schema: {
      type: 'object',
      properties: {
        threadId: {
          type: 'number',
          description: 'ID of the thread to post the message in',
          example: 1,
        },
        role: {
          type: 'string',
          enum: Object.values(AgentMessageRole),
          description: 'Message role (defaults to USER)',
          example: 'USER',
        },
        metadata: {
          type: 'object',
          nullable: true,
          description: 'Custom metadata for the message',
          example: { source: 'web' },
        },
        blocks: {
          type: 'array',
          nullable: true,
          description:
            'Array of message blocks (text, tool calls, charts, etc.)',
          items: {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                enum: Object.values(AgentBlockType),
              },
              order: { type: 'number', minimum: 0 },
              content: { type: 'string' },
              status: {
                type: 'string',
                enum: Object.values(AgentBlockStatus),
                default: 'completed',
              },
              toolName: { type: 'string', nullable: true },
              toolInput: { type: 'object', nullable: true },
              toolOutput: { type: 'object', nullable: true },
              chartType: { type: 'string', nullable: true },
              chartData: { type: 'object', nullable: true },
              error: { type: 'string', nullable: true },
              metadata: { type: 'object', nullable: true },
            },
            required: ['type', 'order', 'content'],
          },
        },
      },
      required: ['threadId'],
    },
  })
  @ApiResponse({
    status: 201,
    description: 'Message created successfully',
    schema: {
      type: 'object',
      properties: {
        messageId: { type: 'number', example: 1 },
        threadId: { type: 'number', example: 1 },
        role: {
          type: 'string',
          enum: Object.values(AgentMessageRole),
          example: 'USER',
        },
        status: {
          type: 'string',
          enum: Object.values(AgentMessageStatus),
          example: 'pending',
        },
        metadata: { type: 'object', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        blocks: { type: 'array', items: { type: 'object' } },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this thread',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - thread not found',
  })
  async createMessage(
    @JwtUser() user: AuthUser,
    @Body(new ZodValidationPipe(createMessageDtoSchema)) dto: CreateMessageDto,
  ) {
    const message = await this.messageService.createMessage(user, dto);
    return message;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Get('threads/:threadId/messages')
  @ApiOperation({
    summary: 'Get all messages in an agent conversation thread',
    description:
      'Retrieves all messages in a specific conversation thread, ordered by creation date (oldest first). Only the thread owner can access the messages. Each message includes its blocks (text, tool calls, charts, etc.) ordered by block order.',
  })
  @ApiParam({
    name: 'threadId',
    type: Number,
    description: 'ID of the thread to retrieve messages from',
    example: 1,
  })
  @ApiResponse({
    status: 200,
    description: 'List of messages retrieved successfully',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          messageId: { type: 'number', example: 1 },
          threadId: { type: 'number', example: 1 },
          role: {
            type: 'string',
            enum: Object.values(AgentMessageRole),
            example: 'USER',
          },
          status: {
            type: 'string',
            enum: Object.values(AgentMessageStatus),
            example: 'completed',
          },
          metadata: { type: 'object', nullable: true },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          blocks: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                blockId: { type: 'number' },
                messageId: { type: 'number' },
                type: { type: 'string' },
                order: { type: 'number' },
                content: { type: 'string' },
                status: { type: 'string' },
                toolName: { type: 'string', nullable: true },
                toolInput: { type: 'object', nullable: true },
                toolOutput: { type: 'object', nullable: true },
                chartType: { type: 'string', nullable: true },
                chartData: { type: 'object', nullable: true },
                error: { type: 'string', nullable: true },
                metadata: { type: 'object', nullable: true },
              },
            },
          },
        },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this thread',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - thread not found',
  })
  async getThreadMessages(
    @JwtUser() user: AuthUser,
    @Param('threadId', ParseIntPipe) threadId: number,
  ) {
    const messages = await this.messageService.getThreadMessages(
      user,
      threadId,
    );
    return messages;
  }

  @UseGuards(AuthGuard('jwt'), UserTypeGuard)
  @ApiBearerAuth()
  @Get('messages/:messageId')
  @ApiOperation({
    summary: 'Get a message by ID',
    description:
      "Retrieves a specific message by ID. Verifies that the user has access to the message's thread before returning it. The message includes all its blocks ordered by block order.",
  })
  @ApiParam({
    name: 'messageId',
    type: Number,
    description: 'ID of the message to retrieve',
    example: 1,
  })
  @ApiResponse({
    status: 200,
    description: 'Message retrieved successfully',
    schema: {
      type: 'object',
      properties: {
        messageId: { type: 'number', example: 1 },
        threadId: { type: 'number', example: 1 },
        role: {
          type: 'string',
          enum: Object.values(AgentMessageRole),
          example: 'USER',
        },
        status: {
          type: 'string',
          enum: Object.values(AgentMessageStatus),
          example: 'completed',
        },
        metadata: { type: 'object', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        blocks: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              blockId: { type: 'number' },
              messageId: { type: 'number' },
              type: { type: 'string' },
              order: { type: 'number' },
              content: { type: 'string' },
              status: { type: 'string' },
              toolName: { type: 'string', nullable: true },
              toolInput: { type: 'object', nullable: true },
              toolOutput: { type: 'object', nullable: true },
              chartType: { type: 'string', nullable: true },
              chartData: { type: 'object', nullable: true },
              error: { type: 'string', nullable: true },
              metadata: { type: 'object', nullable: true },
            },
          },
        },
      },
    },
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized - invalid or missing authentication token',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden - user cannot access this message',
  })
  @ApiResponse({
    status: 404,
    description: 'Not found - message not found',
  })
  async getMessageById(
    @JwtUser() user: AuthUser,
    @Param('messageId', ParseIntPipe) messageId: number,
  ) {
    const message = await this.messageService.getMessageById(user, messageId);
    return message;
  }
}
