/**
 * Zod Schemas for Training Plan Generation
 *
 * These schemas define the data structures used throughout the plan generation workflow.
 * All agents and workflow steps use these schemas for type safety and validation.
 *
 * Data Flow:
 * AthleteFacts → MacroPlan → MesoBlocks → WeekIntentions → ScheduledWeeks → ValidationReport
 */
import { z } from 'zod';

// ============================================================================
// ATHLETE FACTS
// ============================================================================

/**
 * Comprehensive athlete profile data used for plan generation
 * Generated by: athlete-profile.agent
 * Used by: All planning agents
 */
export const athleteFactsSchema = z.object({
  // Basic profile
  athleteId: z.number(),
  name: z.string().nullish(),
  email: z.string().nullish(),

  // Current fitness baseline
  currentFitness: z.object({
    recentWeeklyVolume: z
      .number()
      .describe('Average weekly volume in seconds over last 4 weeks'),
    recentWeeklyDistance: z
      .number()
      .describe('Average weekly distance in meters'),
    longestRecentRun: z
      .number()
      .describe('Longest run in last 8 weeks (meters)'),
    currentLoad: z.object({
      weeklyTrimp: z.number().describe('Current weekly TRIMP'),
      acuteChronicRatio: z.number().describe('Acute:Chronic workload ratio'),
    }),
  }),

  // Availability
  availability: z.array(
    z.object({
      dayOfWeek: z.number().describe('0=Sunday, 1=Monday, ..., 6=Saturday'),
      startTime: z.string().describe('HH:mm format'),
      endTime: z.string().describe('HH:mm format'),
      priority: z.enum(['LOW', 'MEDIUM', 'HIGH']),
    }),
  ),

  // Constraints
  constraints: z.object({
    maxWeeklyVolume: z
      .number()
      .nullish()
      .describe('Maximum weekly volume in seconds'),
    preferredRestDays: z
      .array(z.number())
      .nullish()
      .describe('Preferred rest days (0-6)'),
    avoidDays: z
      .array(z.number())
      .nullish()
      .describe('Days to avoid training (0-6)'),
    injuries: z
      .array(z.string())
      .nullish()
      .describe('Current or recent injuries'),
  }),

  // Experience & preferences
  experienceLevel: z
    .enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ELITE'])
    .nullish(),
  trainingHistory: z
    .string()
    .nullish()
    .describe('Narrative summary of training background'),
});

export type AthleteFacts = z.infer<typeof athleteFactsSchema>;

// ============================================================================
// MACRO PLAN
// ============================================================================

/**
 * High-level training plan structure with phases
 * Generated by: macro-plan.agent
 * Used by: meso-plan.agent
 */
export const macroPlanPhaseSchema = z.object({
  name: z.string().describe('Phase name, e.g., "Base Building Phase 1"'),
  phase: z.enum(['BASE', 'SPECIFIC', 'TAPER', 'RECOVERY', 'COMPETITION']),
  startDate: z.string().describe('ISO date string'),
  endDate: z.string().describe('ISO date string'),
  durationWeeks: z.number().describe('Number of weeks in this phase'),
  targetWeeklyVolume: z
    .object({
      min: z.number().describe('Minimum weekly volume in seconds'),
      max: z.number().describe('Maximum weekly volume in seconds'),
    })
    .describe('Target volume range for this phase'),
  volumeProgression: z
    .enum(['LINEAR', 'STEPPED', 'UNDULATING'])
    .describe('How volume progresses within phase'),
  focus: z.string().describe('Main training focus for this phase'),
  keyWorkouts: z
    .array(z.string())
    .describe('Types of key workouts in this phase'),
});

export const macroPlanMilestoneSchema = z.object({
  date: z.string().describe('ISO date string'),
  type: z.enum(['TEST', 'RACE', 'CHECKPOINT']),
  name: z.string().describe('Milestone name'),
  description: z.string().describe('Details about this milestone'),
});

export const macroPlanSchema = z.object({
  totalDurationWeeks: z.number().describe('Total plan duration in weeks'),
  phases: z.array(macroPlanPhaseSchema),
  milestones: z.array(macroPlanMilestoneSchema),
  overallStrategy: z
    .string()
    .describe('Narrative description of the macro plan strategy'),
  progressionRationale: z
    .string()
    .describe('Explanation of why this progression was chosen'),
});

export type MacroPlan = z.infer<typeof macroPlanSchema>;
export type MacroPlanPhase = z.infer<typeof macroPlanPhaseSchema>;
export type MacroPlanMilestone = z.infer<typeof macroPlanMilestoneSchema>;

// ============================================================================
// MESO BLOCKS
// ============================================================================

/**
 * Weekly training blocks within a phase
 * Generated by: meso-plan.agent
 * Used by: micro-plan.agent
 */
export const mesoWeekSchema = z.object({
  weekNumber: z
    .number()
    .describe('Week number within the entire plan (1, 2, 3, ...)'),
  startDate: z.string().describe('ISO date string'),
  endDate: z.string().describe('ISO date string'),
  theme: z
    .string()
    .describe('Week theme, e.g., "VO2max intervals", "Base building"'),
  targetVolume: z.number().describe('Target weekly volume in seconds'),
  targetLoad: z.number().nullish().describe('Target training load (TRIMP)'),
  intensityFocus: z
    .enum(['EASY', 'MODERATE', 'HARD', 'MIXED'])
    .describe('Primary intensity focus for the week'),
  isRecoveryWeek: z.boolean().describe('Whether this is a recovery week'),
});

export const mesoBlockSchema = z.object({
  blockNumber: z.number().describe('Block number within the phase'),
  phaseName: z.string().describe('Name of the parent phase'),
  weeks: z.array(mesoWeekSchema),
  blockTheme: z.string().describe('Overall theme for this 3-4 week block'),
  progressionPattern: z
    .string()
    .describe('How the block progresses (e.g., "3 weeks build + 1 recovery")'),
});

export type MesoBlock = z.infer<typeof mesoBlockSchema>;
export type MesoWeek = z.infer<typeof mesoWeekSchema>;

// ============================================================================
// WEEK INTENTIONS (Micro Plan)
// ============================================================================

/**
 * Specific session plans for a week (before scheduling)
 * Generated by: micro-plan.agent
 * Used by: scheduling.agent
 */
export const sessionIntentionSchema = z.object({
  sessionId: z.string().nullish().describe('Unique identifier for tracking'),
  type: z
    .enum([
      'INTERVAL',
      'LONG_RUN',
      'TEMPO',
      'EASY',
      'RECOVERY',
      'STRENGTH',
      'RACE',
    ])
    .describe('Session type'),
  sport: z.enum(['RUNNING', 'CYCLING', 'SWIMMING', 'STRENGTH', 'OTHER']),
  targetDuration: z.number().describe('Target duration in seconds'),
  targetDistance: z.number().nullish().describe('Target distance in meters'),
  targetElevationGain: z
    .number()
    .nullish()
    .describe('Target elevation gain in meters'),
  targetIntensity: z
    .object({
      zone: z.string().nullish().describe('Training zone (Z1, Z2, Z3, Z4, Z5)'),
      rpe: z.number().min(0).max(1).describe('RPE on 0-1 scale'),
    })
    .describe('Target intensity metrics'),
  description: z.string().describe('Detailed session description'),
  structure: z
    .any()
    .nullish()
    .describe('Structured workout definition (if applicable)'),
  dayOfWeek: z
    .number()
    .nullish()
    .describe('Preferred day (0-6), null if not yet scheduled'),
  priority: z
    .enum(['HIGH', 'MEDIUM', 'LOW'])
    .describe('Session priority for scheduling'),
});

export const weekIntentionsSchema = z.object({
  weekNumber: z.number(),
  startDate: z.string(),
  endDate: z.string(),
  theme: z.string(),
  targetVolume: z.number(),
  sessions: z.array(sessionIntentionSchema),
});

export type WeekIntentions = z.infer<typeof weekIntentionsSchema>;
export type SessionIntention = z.infer<typeof sessionIntentionSchema>;

// ============================================================================
// SCHEDULED WEEKS
// ============================================================================

/**
 * Sessions assigned to specific calendar days/times
 * Generated by: scheduling.agent
 * Used by: qa.agent, save-plan.tool
 */
export const scheduledSessionSchema = sessionIntentionSchema.extend({
  scheduledDate: z.string().describe('ISO datetime when session is scheduled'),
  scheduledTime: z.string().nullish().describe('Start time in HH:mm format'),
  availabilitySlotId: z
    .number()
    .nullish()
    .describe('ID of the availability slot used'),
});

export const scheduledWeekSchema = z.object({
  weekNumber: z.number(),
  startDate: z.string(),
  endDate: z.string(),
  theme: z.string(),
  targetVolume: z.number(),
  sessions: z.array(scheduledSessionSchema),
  schedulingWarnings: z
    .array(z.string())
    .nullish()
    .describe('Warnings about scheduling compromises or near-violations'),
  unscheduledSessions: z
    .array(sessionIntentionSchema)
    .nullish()
    .describe('Sessions that could not be placed'),
  schedulingNotes: z
    .string()
    .nullish()
    .describe('Overall explanation of scheduling strategy'),
});

export type ScheduledWeek = z.infer<typeof scheduledWeekSchema>;
export type ScheduledSession = z.infer<typeof scheduledSessionSchema>;

// ============================================================================
// VALIDATION REPORT
// ============================================================================

/**
 * Plan validation results
 * Generated by: qa.agent (using validate-plan.tool)
 * Used by: workflow for decision making
 */
export const validationErrorSchema = z.object({
  type: z.enum([
    'LOAD_SPIKE',
    'INSUFFICIENT_RECOVERY',
    'CONSECUTIVE_HARD',
    'DURATION_OVERFLOW',
    'INTENSITY_IMBALANCE',
    'INADEQUATE_PREP',
    'TAPER_ISSUE',
    'STRUCTURE_ISSUE',
  ]),
  severity: z.enum(['CRITICAL', 'WARNING', 'INFO']),
  description: z.string(),
  affectedWeeks: z.array(z.number()).nullish(),
  affectedSessions: z.array(z.number()).nullish(),
  currentValue: z.number().nullish(),
  expectedValue: z.number().nullish(),
  suggestion: z.string(),
});

export const validationMetricsSchema = z.object({
  averageWeeklyVolume: z.number().describe('Average weekly volume in seconds'),
  totalPlanVolume: z.number().describe('Total plan volume in seconds'),
  largestWeeklyIncrease: z
    .number()
    .describe('Largest week-to-week volume increase percentage'),
  easyHardRatio: z.number().describe('Ratio of easy to hard volume'),
  totalRestDays: z.number().describe('Total rest days in plan'),
  recoveryWeeksCount: z.number().describe('Number of recovery weeks'),
  longestRun: z.number().describe('Longest run distance in meters'),
  averageSessionsPerWeek: z.number().describe('Average sessions per week'),
});

export const validationReportSchema = z.object({
  valid: z.boolean().describe('True if no CRITICAL errors'),
  overallScore: z
    .number()
    .min(0)
    .max(100)
    .describe('Plan quality score (0-100)'),
  summary: z.string().describe('Human-readable validation summary'),
  errors: z.array(validationErrorSchema),
  metrics: validationMetricsSchema,
});

export type ValidationReport = z.infer<typeof validationReportSchema>;
export type ValidationError = z.infer<typeof validationErrorSchema>;
export type ValidationMetrics = z.infer<typeof validationMetricsSchema>;

// ============================================================================
// COMPLETE PLAN (For Persistence)
// ============================================================================

/**
 * Complete training plan ready for database persistence
 * Generated by: Combination of all workflow steps
 * Used by: save-plan.tool
 */
export const completePlanSchema = z.object({
  // Plan metadata
  name: z.string(),
  description: z.string().nullish(),
  goal: z.string(),
  startDate: z.string(),
  endDate: z.string(),

  // Structured plan data
  cycles: z.array(
    z.object({
      name: z.string(),
      phase: z.enum(['BASE', 'SPECIFIC', 'TAPER', 'RECOVERY', 'COMPETITION']),
      startDate: z.string(),
      endDate: z.string(),
      weeks: z.array(scheduledWeekSchema),
    }),
  ),

  // Validation results
  validationReport: validationReportSchema,
});

export type CompletePlan = z.infer<typeof completePlanSchema>;

// ============================================================================
// HELPER UTILITIES
// ============================================================================

/**
 * Convert MacroPlan phases to cycle structure for database
 */
export function macroPlanToCycles(
  macroPlan: MacroPlan,
  scheduledWeeks: ScheduledWeek[],
) {
  return macroPlan.phases.map((phase) => {
    // Find weeks that belong to this phase
    const phaseStartDate = new Date(phase.startDate);
    const phaseEndDate = new Date(phase.endDate);

    const phaseWeeks = scheduledWeeks.filter((week) => {
      const weekStart = new Date(week.startDate);
      return weekStart >= phaseStartDate && weekStart < phaseEndDate;
    });

    return {
      name: phase.name,
      phase: phase.phase,
      startDate: phase.startDate,
      endDate: phase.endDate,
      weeks: phaseWeeks,
    };
  });
}

/**
 * Generate a plan name from goal
 */
export function generatePlanName(goal: {
  raceName: string;
  raceDate: string;
}): string {
  const raceDate = new Date(goal.raceDate);
  const month = raceDate.toLocaleString('en-US', { month: 'long' });
  const year = raceDate.getFullYear();
  return `${goal.raceName} - ${month} ${year}`;
}
